export const CURRENCY_LIST_REQUEST = 'CURRENCY_LIST_REQUEST'
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS'
export const CURRENCY_LIST_FAIL = 'CURRENCY_LIST_FAIL'

export const CURRENCY_ADD_REQUEST = 'CURRENCY_ADD_REQUEST'
export const CURRENCY_ADD_SUCCESS = 'CURRENCY_ADD_SUCCESS'
export const CURRENCY_ADD_FAIL = 'CURRENCY_ADD_FAIL'

export const CURRENCY_DELETE_REQUEST = 'CURRENCY_DELETE_REQUEST'
export const CURRENCY_DELETE_SUCCESS = 'CURRENCY_DELETE_SUCCESS'
export const CURRENCY_DELETE_FAIL = 'CURRENCY_DELETE_FAIL'